In [1]:
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
x = iris.data
y = iris.target
x.shape, y.shape, type(x), type(y)

((150, 4), (150,), numpy.ndarray, numpy.ndarray)

In [4]:
import numpy as np
np.unique(y)

array([0, 1, 2])

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y)

x_train.shape, x_test.shape, y_test.shape, y_test.shape

((112, 4), (38, 4), (38,), (38,))

In [6]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()

In [7]:
log.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [8]:
log.coef_, log.intercept_

(array([[ 0.35067558,  1.38836964, -2.09539072, -0.98095218],
        [ 0.64941129, -1.7901503 ,  0.37662276, -1.19112125],
        [-1.5764066 , -1.23324636,  2.2060244 ,  2.27538158]]),
 array([ 0.24391698,  0.85560274, -1.12240078]))

In [9]:
log.predict_proba(x_train[100:104])

array([[8.03091714e-01, 1.96738474e-01, 1.69812277e-04],
       [8.49294409e-01, 1.50664805e-01, 4.07854579e-05],
       [5.49413691e-04, 4.37294843e-01, 5.62155743e-01],
       [3.23346395e-02, 7.53890810e-01, 2.13774551e-01]])

In [10]:
log.predict(x_train[100:104])

array([0, 0, 2, 1])

In [14]:
from sklearn import metrics

In [15]:
y_pred = log.predict(x_train)
y_pred.shape,y_train.shape

((112,), (112,))

In [16]:
print(metrics.classification_report(y_train, y_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        35
          1       0.97      0.90      0.93        39
          2       0.90      0.97      0.94        38

avg / total       0.96      0.96      0.96       112



In [17]:
metrics.confusion_matrix(y_train, y_pred)

array([[35,  0,  0],
       [ 0, 35,  4],
       [ 0,  1, 37]], dtype=int64)